name: 'Milk changing room '
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: 'Milk changing room '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0e10'
    - '#e1ccaf'
    - '#393335'
    - '#797b92'
    - '#966032'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
